INSCRIPTION = 1
LISTE_FILMS = 2
LISTE_UTILISATEURS = 3

MISE_A_JOUR_UTILISATEUR = 4

MESSAGE_INSTANTANE = 5
JOINDRE_SALON = 6
INSCRIPTION_ACCEPTEE = 7
INSCRIPTION_REFUSEE = 8
DESINSCRIPTION = 9
REDIR_MESSAGE_INSTANTANE = 10

JOINDRE_SALON_OK = 11
JOINDRE_SALON_NOK = 12
ACK = 63

MAX_SIZE_USER_NAME = 127
TIME_BEFORE_RESEND = 1.0
MAX_NUMBER_OF_RESEND = 10 
